const axios = require('axios');
const cheerio = require('cheerio');

const urls = ['https://www.wsj.com/market-data/quotes/000010.SZ/financials',
'https://www.wsj.com/market-data/quotes/011170.KS/financials',
'https://www.wsj.com/market-data/quotes/011170.KS/financials',
'https://www.wsj.com/market-data/quotes/0388.HK/financials',
'https://www.wsj.com/market-data/quotes/0388.HK/financials',
'https://www.wsj.com/market-data/quotes/051910.KS/financials',
'https://www.wsj.com/market-data/quotes/0848.HK/financials',
'https://www.wsj.com/market-data/quotes/1010.SE/financials',
'https://www.wsj.com/market-data/quotes/1010.SR/financials',
'https://www.wsj.com/market-data/quotes/1150.SE/financials',
'https://www.wsj.com/market-data/quotes/1150.SR/financials',
'https://www.wsj.com/market-data/quotes/1177.HK/financials',
'https://www.wsj.com/market-data/quotes/1177.HK/financials',
'https://www.wsj.com/market-data/quotes/1211.SE/financials',
'https://www.wsj.com/market-data/quotes/1211.SR/financials',
'https://www.wsj.com/market-data/quotes/2317.TW/financials',
'https://www.wsj.com/market-data/quotes/2318.HK/financials',
'https://www.wsj.com/market-data/quotes/2328.HK/financials',
'https://www.wsj.com/market-data/quotes/2328.HK/financials',
'https://www.wsj.com/market-data/quotes/3908.HK/financials',
'https://www.wsj.com/market-data/quotes/3908.HK/financials',
'https://www.wsj.com/market-data/quotes/4005.T/financials',
'https://www.wsj.com/market-data/quotes/4005.T/financials',
'https://www.wsj.com/market-data/quotes/4183.T/financials',
'https://www.wsj.com/market-data/quotes/4183.T/financials',
'https://www.wsj.com/market-data/quotes/4202.T/financials',
'https://www.wsj.com/market-data/quotes/5801.T/financials',
'https://www.wsj.com/market-data/quotes/5801.T/financials',
'https://www.wsj.com/market-data/quotes/5MIA.F/financials',
'https://www.wsj.com/market-data/quotes/601318.SS/financials',
'https://www.wsj.com/market-data/quotes/6305.T/financials',
'https://www.wsj.com/market-data/quotes/6305.T/financials',
'https://www.wsj.com/market-data/quotes/7010.SE/financials',
'https://www.wsj.com/market-data/quotes/7010.SR/financials',
'https://www.wsj.com/market-data/quotes/7AB1.SG/financials',
'https://www.wsj.com/market-data/quotes/8242.T/financials',
'https://www.wsj.com/market-data/quotes/8242.T/financials',
'https://www.wsj.com/market-data/quotes/ACIW/financials',
'https://www.wsj.com/market-data/quotes/ADCB.AD/financials',
'https://www.wsj.com/market-data/quotes/AEMO/financials',
'https://www.wsj.com/market-data/quotes/AKU/financials',
'https://www.wsj.com/market-data/quotes/AKZA.AS/financials',
'https://www.wsj.com/market-data/quotes/AKZA.AS/financials',
'https://www.wsj.com/market-data/quotes/ALICORC1.LM/financials',
'https://www.wsj.com/market-data/quotes/ALV.DE/financials',
'https://www.wsj.com/market-data/quotes/AMAT/financials',
'https://www.wsj.com/market-data/quotes/AMC/financials',
'https://www.wsj.com/market-data/quotes/AMCR/financials',
'https://www.wsj.com/market-data/quotes/ATGE/financials',
'https://www.wsj.com/market-data/quotes/ATR/financials',
'https://www.wsj.com/market-data/quotes/ATVI/financials',
'https://www.wsj.com/market-data/quotes/AVAL/financials',
'https://www.wsj.com/market-data/quotes/AXAHY/financials',
'https://www.wsj.com/market-data/quotes/AZSEY/financials',
'https://www.wsj.com/market-data/quotes/BAP.AX/financials',
'https://www.wsj.com/market-data/quotes/BAP.AX/financials',
'https://www.wsj.com/market-data/quotes/BLX.TO/financials',
'https://www.wsj.com/market-data/quotes/BMN.L/financials',
'https://www.wsj.com/market-data/quotes/BMN.L/financials',
'https://www.wsj.com/market-data/quotes/BPIRY/financials',
'https://www.wsj.com/market-data/quotes/BTPN.JK/financials',
'https://www.wsj.com/market-data/quotes/BTPN.JK/financials',
'https://www.wsj.com/market-data/quotes/BYDDF/financials',
'https://www.wsj.com/market-data/quotes/CC/financials',
'https://www.wsj.com/market-data/quotes/CC/financials',
'https://www.wsj.com/market-data/quotes/CIMB.KL/financials',
'https://www.wsj.com/market-data/quotes/CNC/financials',
'https://www.wsj.com/market-data/quotes/COHR/financials',
'https://www.wsj.com/market-data/quotes/CRN.AX/financials',
'https://www.wsj.com/market-data/quotes/CRN.AX/financials',
'https://www.wsj.com/market-data/quotes/CSH/financials',
'https://www.wsj.com/market-data/quotes/CSH.DE/financials',
'https://www.wsj.com/market-data/quotes/CSTM/financials',
'https://www.wsj.com/market-data/quotes/CTEC.L/financials',
'https://www.wsj.com/market-data/quotes/CTEC.L/financials',
'https://www.wsj.com/market-data/quotes/CWY.AX/financials',
'https://www.wsj.com/market-data/quotes/CWY.AX/financials',
'https://www.wsj.com/market-data/quotes/DAI.DE/financials',
'https://www.wsj.com/market-data/quotes/DCC.L/financials',
'https://www.wsj.com/market-data/quotes/DCC.L/financials',
'https://www.wsj.com/market-data/quotes/DCT/financials',
'https://www.wsj.com/market-data/quotes/DFH/financials',
'https://www.wsj.com/market-data/quotes/DOX/financials',
'https://www.wsj.com/market-data/quotes/DVN/financials',
'https://www.wsj.com/market-data/quotes/EC/financials',
'https://www.wsj.com/market-data/quotes/ECOR3.SA/financials',
'https://www.wsj.com/market-data/quotes/EDR.MC/financials',
'https://www.wsj.com/market-data/quotes/EDR.MC/financials',
'https://www.wsj.com/market-data/quotes/ENTEL/financials',
'https://www.wsj.com/market-data/quotes/ENTEL.SN/financials',
'https://www.wsj.com/market-data/quotes/ENX/financials',
'https://www.wsj.com/market-data/quotes/ENX.PA/financials',
'https://www.wsj.com/market-data/quotes/EQ/financials',
'https://www.wsj.com/market-data/quotes/EQIX/financials',
'https://www.wsj.com/market-data/quotes/ETR/financials',
'https://www.wsj.com/market-data/quotes/EUROB/financials',
'https://www.wsj.com/market-data/quotes/EUROB.AT/financials',
'https://www.wsj.com/market-data/quotes/GAMUDA/financials',
'https://www.wsj.com/market-data/quotes/GENTERA.MX/financials',
'https://www.wsj.com/market-data/quotes/GENTERA.MX/financials',
'https://www.wsj.com/market-data/quotes/GFC.PA/financials',
'https://www.wsj.com/market-data/quotes/GLO.PS/financials',
'https://www.wsj.com/market-data/quotes/GODREJIND/financials',
'https://www.wsj.com/market-data/quotes/GODREJIND.NS/financials',
'https://www.wsj.com/market-data/quotes/GTMEF/financials',
'https://www.wsj.com/market-data/quotes/HEROMOTOCO.NS/financials',
'https://www.wsj.com/market-data/quotes/HEROMOTOCO.NS/financials',
'https://www.wsj.com/market-data/quotes/HLS.AX/financials',
'https://www.wsj.com/market-data/quotes/HLS.AX/financials',
'https://www.wsj.com/market-data/quotes/HNHPF/financials',
'https://www.wsj.com/market-data/quotes/HTZ/financials',
'https://www.wsj.com/market-data/quotes/HYMTF/financials',
'https://www.wsj.com/market-data/quotes/IBA/financials',
'https://www.wsj.com/market-data/quotes/IBA/financials',
'https://www.wsj.com/market-data/quotes/INTC/financials',
'https://www.wsj.com/market-data/quotes/IRPC.BK/financials',
'https://www.wsj.com/market-data/quotes/KO/financials',
'https://www.wsj.com/market-data/quotes/KOG.OL/financials',
'https://www.wsj.com/market-data/quotes/KOG.OL/financials',
'https://www.wsj.com/market-data/quotes/LAUR/financials',
'https://www.wsj.com/market-data/quotes/LGCLF/financials',
'https://www.wsj.com/market-data/quotes/LIC.NZ/financials',
'https://www.wsj.com/market-data/quotes/LIC.NZ/financials',
'https://www.wsj.com/market-data/quotes/LNTA.L/financials',
'https://www.wsj.com/market-data/quotes/MA/financials',
'https://www.wsj.com/market-data/quotes/MBG.DE/financials',
'https://www.wsj.com/market-data/quotes/MODN/financials',
'https://www.wsj.com/market-data/quotes/NBK.KW/financials',
'https://www.wsj.com/market-data/quotes/NBK.KW/financials',
'https://www.wsj.com/market-data/quotes/NOVT/financials',
'https://www.wsj.com/market-data/quotes/NTZ/financials',
'https://www.wsj.com/market-data/quotes/OCI.AS/financials',
'https://www.wsj.com/market-data/quotes/OCN/financials',
'https://www.wsj.com/market-data/quotes/ORDS.QA/financials',
'https://www.wsj.com/market-data/quotes/ORDS.QA/financials',
'https://www.wsj.com/market-data/quotes/OTP.BD/financials',
'https://www.wsj.com/market-data/quotes/OTPBF/financials',
'https://www.wsj.com/market-data/quotes/OUT1V.HE/financials',
'https://www.wsj.com/market-data/quotes/PARA/financials',
'https://www.wsj.com/market-data/quotes/PBR/financials',
'https://www.wsj.com/market-data/quotes/PHI/financials',
'https://www.wsj.com/market-data/quotes/RAD/financials',
'https://www.wsj.com/market-data/quotes/RDS-A/financials',
'https://www.wsj.com/market-data/quotes/RDS-A/financials',
'https://www.wsj.com/market-data/quotes/REV/financials',
'https://www.wsj.com/market-data/quotes/REVRQ/financials',
'https://www.wsj.com/market-data/quotes/RFP/financials',
'https://www.wsj.com/market-data/quotes/RI.PA/financials',
'https://www.wsj.com/market-data/quotes/RI.PA/financials',
'https://www.wsj.com/market-data/quotes/SAMBA/financials',
'https://www.wsj.com/market-data/quotes/SAMP.N0000/financials',
'https://www.wsj.com/market-data/quotes/SAND.ST/financials',
'https://www.wsj.com/market-data/quotes/SAND.ST/financials',
'https://www.wsj.com/market-data/quotes/SCB.BK/financials',
'https://www.wsj.com/market-data/quotes/SCOM.NR/financials',
'https://www.wsj.com/market-data/quotes/SGL.DE/financials',
'https://www.wsj.com/market-data/quotes/SGL.DE/financials',
'https://www.wsj.com/market-data/quotes/SHEL/financials',
'https://www.wsj.com/market-data/quotes/SIME/financials',
'https://www.wsj.com/market-data/quotes/SKGRP/financials',
'https://www.wsj.com/market-data/quotes/STEP/financials',
'https://www.wsj.com/market-data/quotes/SUNPHARMA.NS/financials',
'https://www.wsj.com/market-data/quotes/SUNPHARMA.NS/financials',
'https://www.wsj.com/market-data/quotes/T/financials',
'https://www.wsj.com/market-data/quotes/TA.TO/financials',
'https://www.wsj.com/market-data/quotes/TAC/financials',
'https://www.wsj.com/market-data/quotes/TEL.PH/financials',
'https://www.wsj.com/market-data/quotes/TEL.RO/financials',
'https://www.wsj.com/market-data/quotes/TKA.DE/financials',
'https://www.wsj.com/market-data/quotes/TKC/financials',
'https://www.wsj.com/market-data/quotes/TKC/financials',
'https://www.wsj.com/market-data/quotes/TLX.DE/financials',
'https://www.wsj.com/market-data/quotes/TLX.DE/financials',
'https://www.wsj.com/market-data/quotes/TM/financials',
'https://www.wsj.com/market-data/quotes/TM.MY/financials',
'https://www.wsj.com/market-data/quotes/TPEIR.AT/financials',
'https://www.wsj.com/market-data/quotes/TRE.MC/financials',
'https://www.wsj.com/market-data/quotes/TRIP/financials',
'https://www.wsj.com/market-data/quotes/TRTN/financials',
'https://www.wsj.com/market-data/quotes/TRUE.BK/financials',
'https://www.wsj.com/market-data/quotes/TRUE.BK/financials',
'https://www.wsj.com/market-data/quotes/TUPY3.SA/financials',
'https://www.wsj.com/market-data/quotes/TUPY3.SA/financials',
'https://www.wsj.com/market-data/quotes/UNACEMC1/financials',
'https://www.wsj.com/market-data/quotes/UPH/financials',
'https://www.wsj.com/market-data/quotes/URW/financials',
'https://www.wsj.com/market-data/quotes/URW.AS/financials',
'https://www.wsj.com/market-data/quotes/USB/financials',
'https://www.wsj.com/market-data/quotes/UTI/financials',
'https://www.wsj.com/market-data/quotes/UTI/financials',
'https://www.wsj.com/market-data/quotes/VOYA/financials',
'https://www.wsj.com/market-data/quotes/VPB.SW/financials',
'https://www.wsj.com/market-data/quotes/VPBN.SW/financials',
'https://www.wsj.com/market-data/quotes/WFC/financials',
'https://www.wsj.com/market-data/quotes/WFRD/financials',
'https://www.wsj.com/market-data/quotes/WFTLF/financials',
'https://www.wsj.com/market-data/quotes/WMT/financials',
'https://www.wsj.com/market-data/quotes/ZIM/financials',
'https://www.wsj.com/market-data/quotes/ZO1.DE/financials',
'https://www.wsj.com/market-data/quotes/ZO1.HM/financials',
'https://www.wsj.com/market-data/quotes/ZURN.SW/financials',
'https://www.wsj.com/market-data/quotes/ZURVY/financials',

];

const fetchData = async (url) => {
  // Extract the company ticker from the URL
  const ticker = url.split('/quotes/')[1].split('/')[0];

  try {
    const response = await axios.get(url);
    const html = response.data;
    const $ = cheerio.load(html);

    const tables = $('table.cr_dataTable');

    tables.each((index, table) => {
      const rows = $(table).find('tr');
      rows.each((i, row) => {
        const label = $(row).find('.data_lbl').text().trim();
        const value = $(row).find('.data_data').text().trim();

        if (
          label.toLowerCase().includes('pretax margin')  
        ) {
          console.log(`${ticker}: ${label}: ${value}`);
        }
      });
    });
  } catch (error) {
    console.log(`Error: ${ticker}: ${error.message}`);
  }
};

urls.forEach(async (url) => {
  console.log(`Fetching data for ${url}`);
  await fetchData(url);
  console.log('\n');
});
